AllCops:.rubocop.yml





























    - 'spec/**/*'  Exclude:  Max: 120Layout/LineLength:  Max: 20Metrics/MethodLength:    - 'config/routes.rb'    - 'spec/**/*'  Exclude:Metrics/BlockLength:  Enabled: falseStyle/FrozenStringLiteralComment:  Enabled: falseStyle/Documentation:    - 'tmp/**/*'    - 'vendor/**/*'    - 'node_modules/**/*'    - 'config/**/*'    - 'db/**/*'    - 'bin/**/*'  Exclude:  TargetRubyVersion: 3.2  NewCops: enable